

services:
  db:
    image: mysql:8.0  
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Akshay@123
      MYSQL_DATABASE: django
      MYSQL_USER: akshay
      MYSQL_PASSWORD: Akshay@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    depends_on:
      - db



volumes:
  mysql_data:

