version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    depends_on:
      - db

  db:
    image: mysql:8.0  # You can change to PostgreSQL if needed
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Akshay@123
      MYSQL_DATABASE: django
      MYSQL_USER: akshay
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

