# Generated by Django 5.0.11 on 2025-02-15 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_domain_alter_module_name_module_domain_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.domain'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('domain', 'name')},
        ),
    ]
