# Generated by Django 5.0.11 on 2025-02-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_module_domain_alter_module_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='domain',
        ),
        migrations.AddField(
            model_name='testcase',
            name='name',
            field=models.CharField(default='default', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
